### PR TITLE
gitconfig: alias: out

### PR DESCRIPTION
**Pull request by Farigh**
Since upstream branch is not necessarily origin/$LOCAL_BRANCH, retrieve the tracking branch using git rev-parse.

### CODE REVIEW

**Comment by Farigh** [comment]
I've been using `git rev-parse --abbrev-ref --symbolic-full-name @{upstream} 2>/dev/null` in my custom_git_ps1 and notice it could be of help in your case :)

Added the proposed alias to my config BTW.

With love :p

**Comment by JimmyDurandWesolowski** [comment]
@Farigh https://github.com/JimmyDurandWesolowski/config/pull/1/commits/6154f882f225ea3e0d9c9e33fdd6b043ee299788#diff-6cb0f77b38346e0fed47293bdc6430c6R15 is the `/dev/null` necessary? I could be interesting to retrieve the error and stop, isn't it?
Overall, I really like the style! Thanks a lot!

**Comment by Farigh** [comment]
Patch set updated

I did some improvement to signoff-check as well :)

**Comment by JimmyDurandWesolowski** [comment]
@Farigh Love it, thanks! :)

**Pull request merged**
